name: items_perdidos
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.4
  cloud_firestore: ^5.0.2
  equatable: ^2.0.5
  fake_cloud_firestore: ^3.0.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_storage: ^12.1.0
  firebase_ui_auth: ^1.15.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_gutter: ^1.0.2
  flutter_localizations:
    sdk: flutter
  get_it: ^7.7.0
  intl: ^0.19.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
