// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaU_qIxc_uEw5FWMM29is4DgZdPLbWYJU',
    appId: '1:757678773753:web:684cb79c5d6ab371a89928',
    messagingSenderId: '757678773753',
    projectId: 'acahdos',
    authDomain: 'acahdos.firebaseapp.com',
    storageBucket: 'acahdos.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3puPEGnN8AShcJkgHs-ocXDSF3B6WV_I',
    appId: '1:757678773753:android:b55a02f3a1bc4968a89928',
    messagingSenderId: '757678773753',
    projectId: 'acahdos',
    storageBucket: 'acahdos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtXXcUF633o-zgcnfgy1fRFHQyovQoM18',
    appId: '1:757678773753:ios:d22c2fe02dd57690a89928',
    messagingSenderId: '757678773753',
    projectId: 'acahdos',
    storageBucket: 'acahdos.appspot.com',
    iosBundleId: 'com.example.verygoodcore.items-perdidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtXXcUF633o-zgcnfgy1fRFHQyovQoM18',
    appId: '1:757678773753:ios:3f437591477e763ea89928',
    messagingSenderId: '757678773753',
    projectId: 'acahdos',
    storageBucket: 'acahdos.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaU_qIxc_uEw5FWMM29is4DgZdPLbWYJU',
    appId: '1:757678773753:web:8cd5a287b97f435ba89928',
    messagingSenderId: '757678773753',
    projectId: 'acahdos',
    authDomain: 'acahdos.firebaseapp.com',
    storageBucket: 'acahdos.appspot.com',
  );
}
